# Generated by Django 5.0.2 on 2024-02-20 18:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Yarn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('type', models.CharField(choices=[('1P', '1 ply'), ('2P', '2 ply'), ('4P', '4 ply'), ('DK', 'Double Knitting'), ('AR', 'Aran'), ('CH', 'Chunky'), ('SC', 'Super Chunky')], default='DK', max_length=2)),
                ('weight', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='ProjectSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=128)),
                ('row_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='YarnColour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour_id', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('colour_name', models.CharField(blank=True, max_length=128, null=True)),
                ('num_skeins', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('yarn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.yarn')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectYarn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('yarn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.yarncolour')),
            ],
        ),
    ]
